version: '3'

services:
  login:
    build:
      context: .
      dockerfile: login/dockerfile
    ports:
      - 8081:8081
    depends_on:
      - database

  quiz:
    build:
      context: .
      dockerfile: quiz/dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
  
  worker:
    build:
      context: .
      dockerfile: worker/dockerfile
    depends_on:
      - database
      - worker-redis

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_EXTENSION=uuid-ossp

  worker-redis:
    image: "redis"
    ports:
      - "6379:6379"

  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - quiz
      - login
